# Install MySQL Server 8.0.x
# dnf install mysql-server -y
# Start MySQL Service
# systemctl enable mysqld
# systemctl start mysqld
# Next, We need to change the default root password in order to start using the database service. Use password ExpenseApp@1 or any other as per your choice.
# mysql_secure_installation --set-root-pass ExpenseApp@1

- name: Configuring DB Server
  hosts: localhost
  become: yes
  tasks:
  - name: Install MySQL Server 8.0.x
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: Start and Enable MySql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled:  yes
