# Install MySQL Server 8.0.x
# dnf install mysql-server -y
# Start MySQL Service
# systemctl enable mysqld
# systemctl start mysqld
# Next, We need to change the default root password in order to start using the database service. Use password ExpenseApp@1 or any other as per your choice.
# mysql_secure_installation --set-root-pass ExpenseApp@1

- name: Configuring DB Server
  hosts: localhost
  become: yes
  vars_prompt:  # This has to stay at PLAY level only, inside TASK level did not work.
  - name: mysql_root_password
    prompt: Enter MySql Password of your choice
    private: no

  tasks:
  - name: Install MySQL Server 8.0.x
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: Start and Enable MySql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled:  yes

# sudo mysql
# show databases; -- both works
# systemctl status mysqld -- works
  
  - name: check if mysql root password is already setup or not
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{mysql_root_password}}"
  
# TASK [check if mysql root password is already setup or not] **************************************************************************
# fatal: [localhost]: FAILED! => {"changed": false, "msg": "A MySQL module is required: for Python 2.7 either PyMySQL, or MySQL-python, or for Python 3.X mysqlclient or PyMySQL. Consider setting ansible_python_interpreter to use the intended Python version."}

- name: Install Python dependencies PyMySQL
  ansible.builtin.pip:
    name: PyMySQL